redis:
	image: redis
db:
	image:postgres:9.4
	environment:
		-POSTGRES_HOST_AUTH_METHOD=trust
vote:
	image: prabhavagrawal/vote-app
	ports:
		-5000:80
	link:
		-redis:redis
result: 
	image: prabhavagrawal/result-app
	ports:
		-5001:80
	links:
		-redis:redis
		-db:db
workers:
	image: prabhavagrawal/worker-app
	links:
		-redis:redis
		-db:db
